### ISSUE TITLE
Implement search feature on home page

### ISSUE THREAD

**Issue by benediktscheffel** [benediktscheffel/nodocs#11]
The user should be able to search for collections, files or tags. 

Current Situation:
The ui part is already implemented and filled with mock suggestions that currently do nothing

Target situation:
The logic for this needs to be implemented.
When searching for tags or files the user should get the expected results.
The user should be able to interact with the search results.
Maybe in the same way as with the collectionTile?

**Comment by benediktscheffel** [comment]
I would like to show suggestions only if the user makes an input. If the input field is empty no suggestions should be shown. To shorten load time while making the already built Collection Nodes could be searched for matching display Names to the users input. For searching for tags maybe add a tags suggestion data structure to home model, that is built as soon as the input field for the search is selected.

**Comment by leotschritter** [comment]
Our search feature is now able to search for file names, Tags or texts in documents.
That might be more what a user expects from a search function when managing documents.

So we decided to change the feature of searching for a collection into the feature to search texts in documents.
