### ISSUE TITLE
add scan services to providers and create interfaces for them 

### ISSUE THREAD

**Issue by leotschritter** [benediktscheffel/nodocs#27]
At the moment all services (disregarding the ocrService) of the scan feature are without interfaces and some of them are not even part of the controller providers.
This must be changed in order to have interchangeable services. Maybe we want to change them some day.

**Comment by benediktscheffel** [comment]
When working on this issue I would like the logic of carusel_service to be refactored. Right now the service is building a List of Widgets what imo should be done in ui layer. The service should only provide the data that is needed to build the ui elements.
