### ISSUE TITLE
fix bugs overall

### ISSUE THREAD

**Issue by leotschritter** [benediktscheffel/nodocs#32]
Please check the box if working again:

Home/DeleteDialog:
- [x] cancel does nothing
- [x] confirm does not update the menu

Home/RenameDialog:
- [x] color of selected text looks terrible. Solution: take property with nice color from the save page title and add it to the theme.
- [x] confirm does not update the menu
- [x] After leaving the dialog with cancel the input is not cleared. If you reenter the dialog it holds the previous input which is probably not the expected behaviour.

Home/CreateDialog:
- [x] confirm does not update the menu

Pdf-Viewer:
- [x] tags aren't updated after saving when there is no entry for the file in isar
- [x] Sometimes the count in the search is a multiple of itself

... more bugs will follow soon

**Comment by benediktscheffel** [comment]
The update of the home page after creating / renaming a file is fixed again. On the page needs to be a watch on the HomeModel to recognize changes to the state of the provider.

The rename dialog does not hold the previously entered text. It has the name of the collection/file as default text that should be renamed

**Comment by leotschritter** [comment]
> The update of the home page after creating / renaming a file is fixed again. On the page needs to be a watch on the HomeModel to recognize changes to the state of the provider.
> 
> The rename dialog does not hold the previously entered text. It has the name of the collection/file as default text that should be renamed

Can you please also check if the menu updates after saving a document?

**Comment by benediktscheffel** [comment]
home page updates after saving a document

**Comment by benediktscheffel** [comment]
text selection color is updated. It can be accesed by using ```theme.textSelectionTheme.selectionColor```

**Comment by benediktscheffel** [comment]
The Bug that the pdfviewer is displaying to many search results isn't fixable.
The syncfusion PdfController is counting the results async. When the search results are cleared, while the results aren't completley counted, the search results aren't cleared completely.
Solution for this: Don't start the search while typing. The search now gets initiated when the user presses the search button.
